"""empty message

Revision ID: c2f448f8f2f8
Revises: 4b6fea9af9dd
Create Date: 2019-02-17 17:12:46.177664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f448f8f2f8'
down_revision = '4b6fea9af9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manotes_sharing_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('giver_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['giver_id'], ['manotes_users.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['manotes_notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['manotes_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('manotes_notes', sa.Column('shared', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manotes_notes', 'shared')
    op.drop_table('manotes_sharing_note')
    # ### end Alembic commands ###
